/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.BadConsequence;
import NapakalakiGame.Monster;
import NapakalakiGame.Prize;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author juane
 */
public class MonsterView extends javax.swing.JPanel {

    
    Monster monsterModel;
    public MonsterView() {
        initComponents();
    }

    public void setMonster(Monster monsterModel){
        this.monsterModel = monsterModel;      
      
        this.name.setText(monsterModel.getName());
        this.nivel.setText(Integer.toString(monsterModel.getLevelsGained()));
        URL url = getClass().getResource(monsterModel.getIcon());
        this.carta.setIcon(new ImageIcon(url));
        /*Actualizar badConsequence*/
        this.badConsequencePanel.setBadConsequence(monsterModel.getBadConsequence());
        this.prizePanel.setPrize(monsterModel.getPrice());
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiqueta_name = new javax.swing.JLabel();
        etiqueta_level = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        nivel = new javax.swing.JLabel();
        etiqueta_monster = new javax.swing.JLabel();
        badConsequencePanel = new GUI.BadConsequenceView();
        prizePanel = new GUI.PrizeView();
        carta = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiqueta_name.setText("Name");

        etiqueta_level.setText("Nivel");

        name.setText("nombre");

        nivel.setText("level");

        etiqueta_monster.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiqueta_monster.setText("Monster");

        badConsequencePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        prizePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        carta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Monsters/3 Byakhees de bonanza.png"))); // NOI18N
        carta.setMaximumSize(new java.awt.Dimension(100, 331));
        carta.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prizePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(badConsequencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(etiqueta_monster)
                                .addComponent(etiqueta_name)
                                .addComponent(name)
                                .addComponent(etiqueta_level, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nivel))
                            .addGap(18, 18, 18)
                            .addComponent(carta, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiqueta_monster)
                        .addGap(24, 24, 24)
                        .addComponent(etiqueta_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etiqueta_level)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nivel)
                        .addGap(0, 213, Short.MAX_VALUE))
                    .addComponent(carta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(badConsequencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(prizePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BadConsequenceView badConsequencePanel;
    private javax.swing.JLabel carta;
    private javax.swing.JLabel etiqueta_level;
    private javax.swing.JLabel etiqueta_monster;
    private javax.swing.JLabel etiqueta_name;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nivel;
    private GUI.PrizeView prizePanel;
    // End of variables declaration//GEN-END:variables
}
