
package GUI;

import NapakalakiGame.CombatResult;
import NapakalakiGame.Napakalaki;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Raul
 */
public class NapakalakiView extends javax.swing.JFrame {

    /**
     * Creates new form NapakalakiView
     */
    
    private Napakalaki napakalakiModel;
    private boolean meet_m;    
    private CombatResult combate;
    
    public NapakalakiView() {
        initComponents();
        this.next_turn.setEnabled(false);
        this.combat.setEnabled(false);
        //this.currentMonster.setVisible(false);
        this.setLocationRelativeTo(null); //ponemos ventana Centrada
    }

    public void setNapakalaki(Napakalaki n) throws CloneNotSupportedException{
        
        meet_m = false;
        napakalakiModel = n;

        this.currentPlayer.setPlayer(n.getCurrentPlayer());
        this.napakalakiModel.getCurrentMonster().getBadConsequence().
                adjustToFitTreasureList(napakalakiModel.getCurrentPlayer()
                        .getVisibleTreasures(), napakalakiModel.getCurrentPlayer().getVisibleTreasures());
        
        this.currentPlayer.setNapakalakiModel(napakalakiModel);
        
        
        this.repaint();
    }
   
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_botones = new javax.swing.ButtonGroup();
        principal = new javax.swing.JPanel();
        player_monster = new javax.swing.JPanel();
        currentMonster = new GUI.MonsterView();
        meet_monster = new javax.swing.JToggleButton();
        combat = new javax.swing.JToggleButton();
        next_turn = new javax.swing.JToggleButton();
        etiqueta_combate = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        currentPlayer = new GUI.PlayerView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NAPAKALAKI");

        principal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout player_monsterLayout = new javax.swing.GroupLayout(player_monster);
        player_monster.setLayout(player_monsterLayout);
        player_monsterLayout.setHorizontalGroup(
            player_monsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player_monsterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(currentMonster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        player_monsterLayout.setVerticalGroup(
            player_monsterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player_monsterLayout.createSequentialGroup()
                .addComponent(currentMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        grupo_botones.add(meet_monster);
        meet_monster.setText("Meet the Monster");
        meet_monster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meet_monsterActionPerformed(evt);
            }
        });

        grupo_botones.add(combat);
        combat.setText("Combat");
        combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatActionPerformed(evt);
            }
        });

        grupo_botones.add(next_turn);
        next_turn.setText("Next Turn");
        next_turn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_turnActionPerformed(evt);
            }
        });

        etiqueta_combate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiqueta_combate.setText("Estado combate");

        resultado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resultado.setText("Esperando");

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalLayout.createSequentialGroup()
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(currentPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(player_monster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(principalLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(etiqueta_combate)
                        .addGap(18, 18, 18)
                        .addComponent(resultado)
                        .addGap(119, 119, 119)
                        .addComponent(meet_monster)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(next_turn)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalLayout.createSequentialGroup()
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player_monster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta_combate)
                    .addComponent(resultado)
                    .addComponent(meet_monster)
                    .addComponent(combat)
                    .addComponent(next_turn))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(principal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meet_monsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meet_monsterActionPerformed
       // this.combat.setEnabled(true);
       
        if (this.meet_m == false){
           this.currentMonster.setMonster(napakalakiModel.getCurrentMonster());
            
        }
         if(this.meet_monster.isSelected()){
             
            this.currentPlayer.getMakeVisible().setEnabled(false);
            this.currentMonster.setMonster(napakalakiModel.getCurrentMonster());
            this.currentMonster.setVisible(true);
            this.combat.setEnabled(true);
            this.next_turn.setEnabled(false);
            this.meet_monster.setEnabled(false);
        }  
             this.napakalakiModel.getCurrentMonster().getBadConsequence().adjustToFitTreasureList(napakalakiModel.getCurrentPlayer().getVisibleTreasures(), napakalakiModel.getCurrentPlayer().getVisibleTreasures());
       
            repaint();
    }//GEN-LAST:event_meet_monsterActionPerformed

    

    private void combatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatActionPerformed
      
        if (this.combat.isSelected()) {
            this.meet_monster.setEnabled(false);
            this.next_turn.setEnabled(true);
            this.combat.setEnabled(false);
            this.currentPlayer.getMakeVisible().setEnabled(true);

            try {
                this.resultado.setText(this.napakalakiModel.developCombat().toString());
            } catch (CloneNotSupportedException ex) {
                Logger.getLogger(NapakalakiView.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        try {
            if (this.napakalakiModel.developCombat().toString().equals("CurrentCultist")) {
                currentPlayer.setSectario(true);
                
            } else {
                currentPlayer.setSectario(false);
                

            }
            currentPlayer.setPlayer(napakalakiModel.getCurrentPlayer());
        } catch (CloneNotSupportedException ex) {
            Logger.getLogger(NapakalakiView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
//        this.napakalakiModel.discardHiddenTreasures(napakalakiModel.getCurrentPlayer().getHiddenTreasures());
//        this.napakalakiModel.discardVisibleTreasures(napakalakiModel.getCurrentPlayer().getVisibleTreasures());
        
        this.currentPlayer.setNapakalakiModel(napakalakiModel);
        repaint();
    }//GEN-LAST:event_combatActionPerformed

    private void next_turnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_turnActionPerformed
        
           if(this.next_turn.isSelected()){
            this.combat.setEnabled(false);
            this.next_turn.setEnabled(false);
            this.meet_monster.setEnabled(true);
            this.currentMonster.setMonster(null);//.setVisible(false);
            this.resultado.setText("Esperando");
            this.napakalakiModel.nextTurn();
            this.currentPlayer.getMakeVisible().setEnabled(true);
               try {
                   this.setNapakalaki(napakalakiModel);
               } catch (CloneNotSupportedException ex) {
                   Logger.getLogger(NapakalakiView.class.getName()).log(Level.SEVERE, null, ex);
               }

       

           // this.currentMonster.setMonster(napakalakiModel.getCurrentMonster());
            currentMonster.getInicialIcon();
            repaint();
        }
        else
            this.next_turn.setEnabled(false);

        repaint();
           
    }//GEN-LAST:event_next_turnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton combat;
    private GUI.MonsterView currentMonster;
    private GUI.PlayerView currentPlayer;
    private javax.swing.JLabel etiqueta_combate;
    private javax.swing.ButtonGroup grupo_botones;
    private javax.swing.JToggleButton meet_monster;
    private javax.swing.JToggleButton next_turn;
    private javax.swing.JPanel player_monster;
    private javax.swing.JPanel principal;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
