/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Prize;

/**
 *
 * @author juane
 */
public class PrizeView extends javax.swing.JPanel {

        private Prize prizeModel;

    /**
     * Creates new form PrizeView
     */
    public PrizeView() {
        initComponents();
    }

     public void setPrize(Prize prizeModel) {
        this.prizeModel = prizeModel;
        
        //Atributos de prize
        this.nivel.setText(Integer.toString(prizeModel.getLevels()));
        this.tesoro.setText(Integer.toString(prizeModel.getTreasures()));        
        repaint();
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiqueta_prize = new javax.swing.JLabel();
        etiqueta_level = new javax.swing.JLabel();
        tesoro = new javax.swing.JLabel();
        nivel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        etiqueta_prize.setText("Tesoros");

        etiqueta_level.setText("Nivel");

        tesoro.setText("Tipo tesoro");

        nivel.setText("nivel");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Prize");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiqueta_prize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tesoro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiqueta_level, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta_prize, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tesoro))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta_level)
                    .addComponent(nivel))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiqueta_level;
    private javax.swing.JLabel etiqueta_prize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nivel;
    private javax.swing.JLabel tesoro;
    // End of variables declaration//GEN-END:variables
}
