/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import NapakalakiGame.Treasure;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Raul
 */
public class TreasureView extends javax.swing.JPanel {

    private Treasure treasureModel;
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }

    public void setTreasure(Treasure treasureModel) {
        this.treasureModel = treasureModel;       
        //Atributos del tesoro
        nombre.setText(treasureModel.getName() ); 
        bonus.setText(Integer.toString(treasureModel.getBonus()));
        tipo.setText(treasureModel.getType().toString());
        
        URL url = getClass().getResource(treasureModel.getIcon());
        this.carta.setIcon(new ImageIcon(url));
        
        repaint();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_datos = new javax.swing.JPanel();
        label_tipo = new javax.swing.JLabel();
        label_nombre = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        bonus = new javax.swing.JLabel();
        label_bonus = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        carta = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        panel_datos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label_tipo.setText("Tipo");

        label_nombre.setText("Nombre");

        nombre.setText("NAME");

        bonus.setText("BONUS");

        label_bonus.setText("Bonus");

        tipo.setText("TIPO");

        carta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Treasures/A prueba de babas.jpg"))); // NOI18N

        javax.swing.GroupLayout panel_datosLayout = new javax.swing.GroupLayout(panel_datos);
        panel_datos.setLayout(panel_datosLayout);
        panel_datosLayout.setHorizontalGroup(
            panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datosLayout.createSequentialGroup()
                .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_bonus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bonus)
                    .addComponent(nombre)
                    .addComponent(label_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nombre)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(carta)
                .addGap(0, 0, 0))
        );
        panel_datosLayout.setVerticalGroup(
            panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datosLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carta)
                    .addGroup(panel_datosLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(label_nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_bonus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bonus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_tipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        add(panel_datos, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bonus;
    private javax.swing.JLabel carta;
    private javax.swing.JLabel label_bonus;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_tipo;
    private javax.swing.JLabel nombre;
    private javax.swing.JPanel panel_datos;
    private javax.swing.JLabel tipo;
    // End of variables declaration//GEN-END:variables
}
